[package]
name = "tobu"
version = "0.1.0"
authors = ["Andrew Guerrero <ajguerrer@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1"
serde = "1"
thiserror = "1"

tobu-format = { path = "../tobu-format", version = "0.1.0" }


[dev-dependencies]
serde_derive = "1"
